// Writes docs/design/ui-map.html from what src/docs/uiMap.capture.tsx measured
// (docs/design/assets/ui-map.json and its two screenshots). Run by `mise run docs:ui-map`.
import { readFileSync, writeFileSync } from "node:fs";

const json = "docs/design/assets/ui-map.json";
const out = "docs/design/ui-map.html";
const { captured, width: W, height: H, parts } = JSON.parse(readFileSync(json, "utf8"));
if (!Array.isArray(parts) || parts.length === 0 || parts.some((p) => !p.rect || !p.badge)) throw new Error(`${json}: no parts, or a part without its box`);

const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const pct = (v, d) => `${((v / d) * 100).toFixed(3)}%`;
const numbered = parts.map((p, i) => ({ ...p, n: i + 1 }));
const boxes = numbered.map((p) =>
  `<span class="box" data-n="${p.n}" style="left:${pct(p.rect.x, W)};top:${pct(p.rect.y, H)};width:${pct(p.rect.w, W)};height:${pct(p.rect.h, H)}"></span>`).join("\n");
const marks = numbered.map((p) =>
  `<button type="button" class="mark" data-n="${p.n}" style="left:${pct(p.badge.x, W)};top:${pct(p.badge.y, H)}" aria-label="${p.n}. ${esc(p.name)}">${p.n}</button>`).join("\n");
const groups = [...new Set(numbered.map((p) => p.group))];
const legend = groups.map((g) => `<section><h2>${esc(g)}</h2><ol>${numbered.filter((p) => p.group === g).map((p) =>
  `<li data-n="${p.n}" tabindex="0"><span class="num">${p.n}</span><div><b>${esc(p.name)}</b><p>${esc(p.what)}</p><code>${esc(p.code)}</code></div></li>`).join("")}</ol></section>`).join("");

const dark = "--bg:#111215; --fg:#e8e9ec; --muted:#a4a7b0; --line:#2c2e34; --card:#18191d; --accent:#6f8cff; --accent-fg:#0b0d14; --hl:rgba(111,140,255,.22); color-scheme:dark;";
writeFileSync(out, `<!doctype html>
<!-- Generated by \`mise run docs:ui-map\` (scripts/ui-map.mjs); edit src/docs/uiMap.surfaces.ts, not this file. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Herdr UI Map</title>
<style>
/* Layout: the screenshot with numbered badges on top, the legend in three columns (one per screen column) under it. */
:root { --bg:#f6f7f9; --fg:#1b1d22; --muted:#555963; --line:#d9dce2; --card:#ffffff; --accent:#3a5bd9; --accent-fg:#ffffff; --hl:rgba(58,91,217,.16);
  --sans:-apple-system,BlinkMacSystemFont,"SF Pro Text","Inter",sans-serif; --mono:ui-monospace,"SF Mono",Menlo,monospace; }
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) { ${dark} } }
:root[data-theme="dark"] { ${dark} }
html, body { margin:0; background:var(--bg); color:var(--fg); font:14px/1.5 var(--sans); }
.wrap { max-width:1480px; margin:0 auto; padding-block:24px 48px; padding-inline:16px; display:grid; gap:20px; }
header h1 { margin:0 0 4px; font-size:20px; text-wrap:balance; }
header p { margin:0; color:var(--muted); max-width:78ch; }
header code, li code { font-family:var(--mono); font-size:12px; }
.bar { display:flex; flex-wrap:wrap; gap:8px; align-items:center; }
.bar button { font:inherit; font-size:13px; padding:4px 12px; border-radius:6px; border:1px solid var(--line); background:var(--card); color:var(--fg); cursor:pointer; }
.bar button[aria-pressed="true"] { border-color:var(--accent); box-shadow:inset 0 0 0 1px var(--accent); }
.bar span { color:var(--muted); font-size:13px; }
.shot { position:relative; border:1px solid var(--line); border-radius:10px; overflow:hidden; background:var(--card); }
.shot img { display:block; width:100%; height:auto; }
.shot img[hidden] { display:none; }
.box { position:absolute; border:2px solid var(--accent); background:var(--hl); border-radius:4px; opacity:0; transition:opacity 120ms; pointer-events:none; box-sizing:border-box; }
.box.on { opacity:1; }
.mark { position:absolute; transform:translate(-50%,-50%); min-width:20px; height:20px; padding:0 4px; box-sizing:border-box; border-radius:999px; border:1.5px solid var(--card);
  background:var(--accent); color:var(--accent-fg); font:700 11px/17px var(--sans); text-align:center; cursor:pointer; box-shadow:0 1px 3px rgba(0,0,0,.35); }
.mark.on { outline:2px solid var(--fg); outline-offset:1px; }
.legend { display:grid; grid-template-columns:repeat(auto-fit, minmax(min(100%, 340px), 1fr)); gap:16px; }
.legend section { min-width:0; }
.legend h2 { margin:0 0 6px; font-size:12px; letter-spacing:.08em; text-transform:uppercase; color:var(--muted); }
.legend ol { list-style:none; margin:0; padding:0; display:grid; gap:2px; }
.legend li { display:flex; gap:10px; padding:6px 8px; border-radius:6px; cursor:default; outline:none; }
.legend li.on, .legend li:focus-visible { background:var(--hl); }
.legend li .num { flex:none; width:22px; height:22px; border-radius:999px; background:var(--accent); color:var(--accent-fg); font:700 11px/22px var(--sans); text-align:center; margin-top:1px; }
.legend li div { min-width:0; }
.legend li b { font-weight:600; }
.legend li p { margin:0; color:var(--muted); font-size:13px; }
.legend li code { color:var(--muted); overflow-wrap:anywhere; }
@media (prefers-reduced-motion: reduce) { .box { transition:none; } }
</style></head><body>
<div class="wrap">
<header><h1>Herdr UI map</h1>
<p>The names to use for each part of the screen, in issues, specs and prompts. The picture is the real app rendered from its components with sample data (${esc(captured)}). Point at a number or a name to see the area. The same names are in <code>CONTEXT.md</code> › UI surfaces; <code>mise run docs:ui-map</code> redraws this page.</p></header>
<div class="bar" role="group" aria-label="Screenshot theme"><button type="button" id="t-light" aria-pressed="true">Light</button><button type="button" id="t-dark" aria-pressed="false">Dark</button><span>Light and dark share the same layout.</span></div>
<div class="shot"><img id="img-light" src="assets/ui-map-light.png" alt="Herdr with its parts numbered, light theme" width="${W}" height="${H}"><img id="img-dark" src="assets/ui-map-dark.png" alt="Herdr with its parts numbered, dark theme" width="${W}" height="${H}" hidden>
${boxes}
${marks}
</div>
<div class="legend">${legend}</div>
</div>
<script>
(() => {
  const on = (n, v) => document.querySelectorAll(\`[data-n="\${n}"]\`).forEach((e) => e.classList.toggle("on", v));
  document.querySelectorAll("[data-n]").forEach((e) => {
    const n = e.dataset.n;
    for (const [ev, v] of [["mouseenter", true], ["mouseleave", false], ["focus", true], ["blur", false]]) e.addEventListener(ev, () => on(n, v));
  });
  const light = document.getElementById("img-light"), dark = document.getElementById("img-dark");
  const bl = document.getElementById("t-light"), bd = document.getElementById("t-dark");
  const pick = (d) => { dark.hidden = !d; light.hidden = d; bd.setAttribute("aria-pressed", String(d)); bl.setAttribute("aria-pressed", String(!d)); };
  bl.onclick = () => pick(false); bd.onclick = () => pick(true);
  const root = document.documentElement.dataset.theme;
  pick(root ? root === "dark" : matchMedia("(prefers-color-scheme: dark)").matches);
})();
</script>
</body></html>
`);
console.log(`${out}: ${parts.length} parts (captured ${captured})`);
